[package]
name = "tapo-plug-exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
tapo = "0.7"
tokio = { version = "1.38.0", features = ["full"] }